import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { ThemeProvider } from "@/context/ThemeContext";
import NavbarComponent from "@/components/navbar/navbar";

const prompt = Prompt({ subsets: ["thai"], weight: "400" });

export const metadata: Metadata = {
  title: "VCS IT Center",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={prompt.className}>
        <NextUIProvider>
          <ThemeProvider>
            <NavbarComponent />
            {children}
          </ThemeProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
